-- Korean render-time translations.
-- Internal data, parsing, save files, and calculations remain in English.

return {
	exact = {
		["Options"] = "옵션",
		["About"] = "정보",
		["Save"] = "저장",
		["Cancel"] = "취소",
		["Close"] = "닫기",
		["Dismiss"] = "닫기",
		["Delete"] = "삭제",
		["Edit"] = "편집",
		["New"] = "새로 만들기",
		["Copy"] = "복사",
		["Paste"] = "붙여넣기",
		["Import"] = "가져오기",
		["Export"] = "내보내기",
		["Search"] = "검색",
		["Search:"] = "검색:",
		["Update Ready"] = "업데이트 준비됨",
		["Check for Update"] = "업데이트 확인",
		["PoB Community Fork"] = "PoB 커뮤니티 포크",
		["Dev Mode"] = "개발자 모드",
		["Restarting..."] = "다시 시작 중...",
		["Please wait while we complete installation..."] = "설치를 마무리하는 동안 기다려 주세요...",
		["Loading main script..."] = "메인 스크립트 로딩 중...",
		["No update available."] = "사용 가능한 업데이트가 없습니다.",
		["Checking for update..."] = "업데이트 확인 중...",
		["Downloading update..."] = "업데이트 다운로드 중...",
		["Update is ready."] = "업데이트가 준비되었습니다.",
		["Applying update..."] = "업데이트 적용 중...",

		["Application options"] = "애플리케이션 옵션",
		["Build-related options"] = "빌드 관련 옵션",
		["Connection Protocol:"] = "연결 프로토콜:",
		["Proxy server:"] = "프록시 서버:",
		["UI scaling override:"] = "UI 배율 재정의:",
		["Build save path:"] = "빌드 저장 경로:",
		["Node Power colours:"] = "노드 파워 색상:",
		["Hex colour for positive values:"] = "긍정 값 색상:",
		["Hex colour for negative values:"] = "부정 값 색상:",
		["Hex colour for highlight nodes:"] = "강조 노드 색상:",
		["Opt-in to weekly beta test builds:"] = "주간 베타 빌드 사용:",
		["Show search circles at viewport edge"] = "화면 가장자리 검색 원 표시",
		["Styled Tooltips with Flavour Text:"] = "플레이버 텍스트 툴팁 사용:",
		["Show Animations:"] = "애니메이션 표시:",
		["Show all item affixes sliders:"] = "모든 아이템 속성 슬라이더 표시:",
		["Show thousands separators:"] = "천 단위 구분 기호 표시:",
		["Thousands separator:"] = "천 단위 구분 기호:",
		["Decimal separator:"] = "소수점 구분 기호:",
		["Show build name in window title:"] = "창 제목에 빌드 이름 표시:",
		["Default gem quality:"] = "기본 젬 퀄리티:",
		["Default item quality:"] = "기본 아이템 퀄리티:",
		["Default character level:"] = "기본 캐릭터 레벨:",
		["Default item affix quality:"] = "기본 아이템 속성 품질:",
		["Show build warnings:"] = "빌드 경고 표시:",
		["Show tooltips only for affected slots:"] = "영향받는 슬롯에만 툴팁 표시:",
		["Copy augments onto display item:"] = "표시 아이템에 강화 복사:",
		["Show tooltip for unsupported mods :"] = "미지원 모드 툴팁 표시:",
		["Invert slider scroll direction:"] = "슬라이더 스크롤 방향 반전:",
		["Disable Dev AutoSave:"] = "개발자 자동 저장 비활성화:",
		["Use system default"] = "시스템 기본값 사용",
		["Auto"] = "자동",
		["Red & Blue"] = "빨강 & 파랑",
		["Red & Green"] = "빨강 & 초록",
		["Green & Blue"] = "초록 & 파랑",

		["Tree"] = "패시브 트리",
		["Skills"] = "스킬",
		["Items"] = "아이템",
		["Calcs"] = "계산",
		["Config"] = "설정",
		["Notes"] = "노트",
		["Party"] = "파티",
		["Import/Export Build"] = "빌드 가져오기/내보내기",
		["Trade"] = "거래",
		["Compare"] = "비교",
		["Builds"] = "빌드",
		["Level"] = "레벨",
		["Quality"] = "퀄리티",
		["Enabled"] = "활성화",
		["Disabled"] = "비활성화",
		["Name"] = "이름",
		["Type"] = "종류",
		["Base"] = "베이스",
		["Rarity"] = "희귀도",
		["Source"] = "출처",
		["Variant"] = "변형",
		["Radius"] = "반경",
		["Sockets"] = "소켓",
		["Limited to"] = "제한",
		["Requirements"] = "요구사항",
		["Attributes"] = "능력치",
		["Class"] = "클래스",
		["Ascendancy"] = "전직",
		["Bandit"] = "도적",
		["Pantheon"] = "판테온",
		["Weapon"] = "무기",
		["Shield"] = "방패",
		["Armour"] = "방어도",
		["Evasion"] = "회피",
		["Energy Shield"] = "에너지 보호막",
		["Ward"] = "수호",
		["Life"] = "생명력",
		["Mana"] = "마나",
		["Spirit"] = "정신력",
		["Strength"] = "힘",
		["Dexterity"] = "민첩",
		["Intelligence"] = "지능",
		["Accuracy"] = "정확도",
		["Damage"] = "피해",
		["Defence"] = "방어",
		["Speed"] = "속도",
		["Critical"] = "치명타",
		["Resistance"] = "저항",
		["Fire"] = "화염",
		["Cold"] = "냉기",
		["Lightning"] = "번개",
		["Chaos"] = "카오스",
		["Physical"] = "물리",
		["Elemental"] = "원소",
		["Minion"] = "소환수",
		["Totem"] = "토템",
		["Aura"] = "오라",
		["Curse"] = "저주",
		["Buff"] = "버프",
		["Debuff"] = "디버프",
		["Projectile"] = "투사체",
		["Attack"] = "공격",
		["Spell"] = "주문",
		["Melee"] = "근접",
		["Area"] = "범위",

		["Strength Required"] = "필요 힘",
		["Dexterity Required"] = "필요 민첩",
		["Intelligence Required"] = "필요 지능",
		["Full DPS"] = "전체 DPS",
		["Combined DPS"] = "합산 DPS",
		["Total DPS"] = "총 DPS",
		["Average Damage"] = "평균 피해",
		["Attack Rate"] = "공격 속도",
		["Cast Rate"] = "시전 속도",
		["Crit Chance"] = "치명타 확률",
		["Crit Multiplier"] = "치명타 배율",
		["Hit Chance"] = "명중 확률",
		["Impale DPS"] = "꿰뚫기 DPS",
		["Bleed DPS"] = "출혈 DPS",
		["Ignite DPS"] = "점화 DPS",
		["Poison DPS"] = "독 DPS",
		["Total Pool"] = "총 자원",
		["Maximum Hit Taken"] = "최대 피격 피해",
		["Effective Hit Pool"] = "유효 생존력",
		["Life Regen"] = "생명력 재생",
		["Mana Regen"] = "마나 재생",
		["Energy Shield Regen"] = "에너지 보호막 재생",
		["Movement Speed"] = "이동 속도",
		["Chance to Block"] = "막기 확률",
		["Corrupted"] = "타락",
		["Twice Corrupted"] = "이중 타락",
		["Mirrored"] = "복제됨",
		["Split"] = "분할됨",
		["Sanctified"] = "성역화",
		["Not yet available"] = "아직 사용 불가",
		["Legacy Gem"] = "레거시 젬",
		["Gem only exists in Standard League"] = "스탠다드 리그에만 존재하는 젬",
		["Not supported in PoB yet"] = "아직 PoB에서 지원하지 않음",
		["(Not supported in PoB yet)"] = "(아직 PoB에서 지원하지 않음)",
		["empty"] = "비어 있음",
		["(empty)"] = "(비어 있음)",
		["<No matches>"] = "<일치 없음>",
	},
	patterns = {
		{ "^Version: (.+)$", "버전: %1" },
		{ "^Search: (.+)$", "검색: %1" },
		{ "^(%s*)Level: (.+)$", "%1레벨: %2" },
		{ "^(%s*)Quality: (.+)$", "%1퀄리티: %2" },
		{ "^(%s*)Cost: (.+)$", "%1소모: %2" },
		{ "^(%s*)Reservation: (.+)$", "%1점유: %2" },
		{ "^(%s*)Category: (.+)$", "%1분류: %2" },
		{ "^(%s*)Tier: (.+)$", "%1등급: %2" },
		{ "^(%s*)Requires: (.+)$", "%1요구사항: %2" },
		{ "^Variant: (.+)$", "변형: %1" },
		{ "^Source: (.+)$", "출처: %1" },
		{ "^Sockets: (.+)$", "소켓: %1" },
		{ "^Radius: (.+)$", "반경: %1" },
		{ "^Limited to: (.+)$", "제한: %1" },
		{ "^Requires Class (.+)$", "필요 클래스: %1" },
		{ "^Physical Damage: (.+)$", "물리 피해: %1" },
		{ "^Elemental DPS: (.+)$", "원소 DPS: %1" },
		{ "^Chaos Damage: (.+)$", "카오스 피해: %1" },
		{ "^Total DPS: (.+)$", "총 DPS: %1" },
		{ "^Critical Hit Chance: (.+)$", "치명타 확률: %1" },
		{ "^Attacks per Second: (.+)$", "초당 공격 횟수: %1" },
		{ "^Reload Time: (.+)$", "재장전 시간: %1" },
		{ "^Weapon Range: (.+)$", "무기 사거리: %1" },
		{ "^Chance to Block: (.+)$", "막기 확률: %1" },
		{ "^Armour: (.+)$", "방어도: %1" },
		{ "^Evasion Rating: (.+)$", "회피: %1" },
		{ "^Energy Shield: (.+)$", "에너지 보호막: %1" },
		{ "^Ward: (.+)$", "수호: %1" },
		{ "^Consumes (.+) Charges on use$", "사용 시 충전 %1 소모" },
		{ "^Lasts (.+) Seconds$", "%1초 지속" },
		{ "^Recovers (.+) Life instantly$", "생명력 %1 즉시 회복" },
		{ "^Recovers (.+) Mana instantly$", "마나 %1 즉시 회복" },
		{ "^(.+) Required$", "필요 %1" },
		{ "^(.+):$", "%1:" },
	},
}
